import './globals.css'


import Container from '@/components/container'
import Navbar from '@/components/NavbarDinamic';
import Footer from '@/components/footer';




export const metadata = {
  title: 'Inmodocs V 0.1.0',
  description: 'Generated By Inmodocs',
}

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <head>
        <link rel="icon" href="../public/favicon.ico" sizes="any" />
      </head>


      <body>
        <header className=' sticky top-0'>
          <Navbar />
        </header>
        <main>
          {children}
        </main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  )
}
