import Providers from "@/store/provider";
import "./globals.css";



export const metadata = {
  title: "Inmodocs V 0.1.0",
  description: "Generated By Inmodocs",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body>{children}</body>
      </Providers>
    </html>
  );
}
